---
- name: Install remi repo.
  yum:
    name: "{{ remi_repo_url }}"
    state: present
    validate_certs: "{{ remi_repo_validate_certs }}"

- name: Import remi GPG key.
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: present
